### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [zeromq/majordomo#64]
Hi I see that the LICENSE file is now MPL, but there are still LGPL with exception and GPL licenses.
What is the skinny?
Thanks!

**Comment by pypingou** [comment]
We're almost one year later and the license is still unclear?

**Comment by ajanicij** [comment]
The license is not unclear, it is MPL - I understand that this is the preferred license for all projects in ZeroMQ. COPYING and COPYING.LESSER are remnants from the old convention. We can just remove these files and keep LICENSE, unless someone can see a reason why we need to have COPYING and COPYING.LESSER.

**Comment by bluca** [comment]
I'd recommend taking those 2 files out yes, so to avoid any possible confusion

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/majordomo/pull/66

**Comment by pombredanne** [comment]
Thank you ++ for taking the time to clarify this.

**Comment by pypingou** [comment]
Thanks :)
