### ISSUE TITLE
"Make lookup of reverse DNS records  help" does not work

### ISSUE THREAD

**Issue by bernd-wechner** [zeromq/majordomo#68]
This feature is not functioning on a Turris Omnia I have and Omnia users generally report same:

https://forum.turris.cz/t/how-to-make-dns-resolv-working-in-majordomo/1169/39
https://forum.turris.cz/t/reverse-dns-address-resolution-doesnt-work/1136

Any pointers on diagnosing reasons, and implementing fixes would be gratefully received.

**Comment by bluca** [comment]
I think this is the wrong "majordomo" :-)

This is probably the one you are looking for:

https://gitlab.labs.nic.cz/turris/ucollect/blob/master/src/plugins/majordomo/majordomo.txt

**Comment by bernd-wechner** [comment]
Ha, ha, very good point and thanks for pointing it out ;-). Yes. A polite suggestion is to put in the README.md of this project a good link to a document describing what the Majordomo protocol is, and perhaps a terse summary there too. My lazy brain didn't suspect (sadly) that different projects might have held the same name, but of course, it should really, as it does happen!

**Comment by JensRantil** [comment]
@bernd-wechner README pull requests are welcome! ;)

**Comment by bernd-wechner** [comment]
I'd need some more info one what the Majordomo protocol is and where it's used. Sadly searching the web is not rapidly illuminating, but ti seems to relate to an IPC system called ZeroMQ of which this repo is part and be a protocol that runs over ZeroMQ? Ha, ha, I'm fishing for a clear simple way to express what it is, and what it isn't (a statistics presentation interface for OpenWRT routers).
